package github

type Event struct {
	Name  string
	Label string
	Short string
}

var SupportedEvents = []Event{
	{Name: "branch_protection_configuration", Label: "Branch protection configuration", Short: "bpc"},
	{Name: "branch_protection_rule", Label: "Branch protection rules", Short: "bpr"},
	{Name: "check_run", Label: "Check runs", Short: "cr"},
	{Name: "check_suite", Label: "Check suites", Short: "cs"},
	{Name: "code_scanning_alert", Label: "Code scanning alerts", Short: "csa"},
	{Name: "commit_comment", Label: "Commit comments", Short: "cc"},
	{Name: "content_reference", Label: "Content references", Short: "ctr"},
	{Name: "create", Label: "Branches and tags created", Short: "crt"},
	{Name: "custom_property", Label: "Custom properties", Short: "cp"},
	{Name: "custom_property_values", Label: "Custom property values", Short: "cpv"},
	{Name: "delete", Label: "Branches and tags deleted", Short: "del"},
	{Name: "dependabot_alert", Label: "Dependabot alerts", Short: "da"},
	{Name: "deploy_key", Label: "Deploy keys", Short: "dk"},
	{Name: "deployment", Label: "Deployments", Short: "dep"},
	{Name: "deployment_protection_rule", Label: "Deployment protection rules", Short: "dpr"},
	{Name: "deployment_review", Label: "Deployment reviews", Short: "drv"},
	{Name: "deployment_status", Label: "Deployment statuses", Short: "ds"},
	{Name: "discussion", Label: "Discussions", Short: "dis"},
	{Name: "discussion_comment", Label: "Discussion comments", Short: "dc"},
	{Name: "fork", Label: "Forks", Short: "f"},
	{Name: "github_app_authorization", Label: "GitHub App authorizations", Short: "gaa"},
	{Name: "gollum", Label: "Wikis", Short: "g"},
	{Name: "installation", Label: "Installations", Short: "ins"},
	{Name: "installation_repositories", Label: "Installation repositories", Short: "ir"},
	{Name: "installation_target", Label: "Installation targets", Short: "it"},
	{Name: "issue_comment", Label: "Issue and PR comments", Short: "ic"},
	{Name: "issues", Label: "Issues", Short: "i"},
	{Name: "label", Label: "Labels", Short: "lbl"},
	{Name: "marketplace_purchase", Label: "Marketplace purchases", Short: "mp"},
	{Name: "member", Label: "Repository collaborators", Short: "m"},
	{Name: "membership", Label: "Organization memberships", Short: "mem"},
	{Name: "merge_group", Label: "Merge queue groups", Short: "mg"},
	{Name: "meta", Label: "Webhook lifecycle", Short: "mt"},
	{Name: "milestone", Label: "Milestones", Short: "ms"},
	{Name: "organization", Label: "Organizations", Short: "org"},
	{Name: "org_block", Label: "Organization blocks", Short: "ob"},
	{Name: "package", Label: "Packages", Short: "pkg"},
	{Name: "page_build", Label: "GitHub Pages builds", Short: "pb"},
	{Name: "personal_access_token_request", Label: "PAT requests", Short: "pat"},
	{Name: "ping", Label: "Webhook pings", Short: "ping"},
	{Name: "projects_v2", Label: "Projects v2", Short: "pv2"},
	{Name: "projects_v2_item", Label: "Project v2 items", Short: "pvi"},
	{Name: "public", Label: "Repository visibility", Short: "pub"},
	{Name: "pull_request", Label: "Pull requests", Short: "pr"},
	{Name: "pull_request_review", Label: "Pull request reviews", Short: "prr"},
	{Name: "pull_request_review_comment", Label: "PR review comments", Short: "prc"},
	{Name: "pull_request_review_thread", Label: "PR review threads", Short: "prt"},
	{Name: "pull_request_target", Label: "Pull request target", Short: "pt"},
	{Name: "push", Label: "Pushes", Short: "p"},
	{Name: "registry_package", Label: "Registry packages", Short: "rp"},
	{Name: "release", Label: "Releases", Short: "rel"},
	{Name: "repository", Label: "Repository changes", Short: "rep"},
	{Name: "repository_dispatch", Label: "Repository dispatches", Short: "rd"},
	{Name: "repository_import", Label: "Repository imports", Short: "ri"},
	{Name: "repository_ruleset", Label: "Repository rulesets", Short: "rr"},
	{Name: "repository_vulnerability_alert", Label: "Vulnerability alerts", Short: "rva"},
	{Name: "secret_scanning_alert", Label: "Secret scanning alerts", Short: "ssa"},
	{Name: "secret_scanning_alert_location", Label: "Secret scanning locations", Short: "ssl"},
	{Name: "security_advisory", Label: "Security advisories", Short: "sa"},
	{Name: "security_and_analysis", Label: "Security and analysis", Short: "saa"},
	{Name: "sponsorship", Label: "Sponsorships", Short: "sp"},
	{Name: "star", Label: "Stars", Short: "s"},
	{Name: "status", Label: "Commit statuses", Short: "st"},
	{Name: "team", Label: "Teams", Short: "tm"},
	{Name: "team_add", Label: "Team repository access", Short: "ta"},
	{Name: "user", Label: "Users", Short: "u"},
	{Name: "watch", Label: "Watches", Short: "w"},
	{Name: "workflow_dispatch", Label: "Workflow dispatches", Short: "wd"},
	{Name: "workflow_job", Label: "Workflow jobs", Short: "wj"},
	{Name: "workflow_run", Label: "Workflow runs", Short: "wr"},
}
